# by default Travis uses JDK 8u31, which is much too old for Scala 2.12 (versions before 8u102 have issues - https://issues.scala-lang.org/browse/SI-9828)
dist: trusty
sudo: false

language: scala

jdk:
  - openjdk11

scala:
  - 2.13.0
  - 2.12.9

script: sbt ++$TRAVIS_SCALA_VERSION clean coverage test

after_success: 'if [ "$TRAVIS_PULL_REQUEST" = "false" ]; then sbt ++$TRAVIS_SCALA_VERSION coverageReport coveralls; fi'

notifications:
  slack:
    on_success: never
    on_failure: always
    rooms:
      secure: "NoNtiUp3jB2L8VIPmVzyQuQ2I7UCxqpikXzux3BM83a6V4eMC28RuRQRbiMtCL6wAtc7Ied1WBFcFxi8lMOz4jwyKz9fnNTTWHyYOgPbZae8mAMNEJ+ISq/zM3JHp/1tqyQlPD14OSW5uBQX+lIPce/g+GRWaLYKJWkYLEGE5is/32zEY09UsR37WpWiUF98tfzghuPzv0NfHKtpp+Zh3t9dZrDp2l7ddi2NzTpHk7bkNNpQeSFtUHw0tprxndi+4nCPt4WNbbA35vWgabdToBQDZmyE9GbQA2nOAok8WOpb2PlHBHD6f21re20OB/QGxoMw25GOk0LXU0YsPtWWy1riC/E6tIqzcUuAx64uNVQ4+C5exaAErDFJX+dnsc/DMof6UrrGMzlGuQuvXC7hAYJQ+emICXz0UWrt5GYT9WzoPhRhf6vZLR9p9zJHIouW+gOvQzaOC8/9dnAS0Weywu6Fc3Je1GeL6v5HmfPV/Of1mmqWkfzOGCdJH+adG0AEFmSuiXqVIX6sK1L6cHNFcHHBGpqfp/a+9jd0Ne/IZdQVOURZUQDtbOR31pzv1v/a0jr/2kJW2Dt6C/oTcN7vr/BoiNnUdxCLnwXMOIJNJ1CvUDfdovhZwKfwtbQV+CghXOYI6dlX8MqbjCwtaSY6pQF0cYA93coQo+ojZtEu1Ow="

cache:
  directories:
    - $HOME/.ivy2/cache
    - $HOME/.sbt

before_cache:
  - find $HOME/.ivy2/cache -name "ivydata-*.properties" -print -delete
  - find $HOME/.sbt        -name "*.lock"               -print -delete